# A sample workflow 

*Hi Victor, it's Lizzie. I will just put my notes to you in italics. You really should remove them. In general, I suggest you focus on getting some code/plots and basic text done that you then share next week with everyone.*

To show our workflow in action, we examine a subset of the Living Planet Index (LPI, download at: https://www.livingplanetindex.org/data_portal. This download should include a csv file, here: LPD2022_public.csv, that we use below). For more information on the LPI, check out the main text and www.livingplanetindex.org/. 

## Step 1: Research question

*I started this, but it would be perfect for JD to fix/add to, so I did not finish it. (As mentioned above, I suggest you focus on getting some code/plots and basic text done that you then share next week with everyone.)*

Here we need to focus on exactly what question we are trying to answer, which will guide us in the next steps. This step is sometimes skipped over or moved through so quickly that the exact question is not clear, but is critical for developing a useful model. We might start with: What is the global trend for biodiversity in vetebrate species? This is rather broad and might mean we should develop a model that will yield one global estimate. In thinking about this, we might realize we don't want just that, we actually want to understand the variation across different species and perhaps populations and also a global estimate. So we might refine the question to:  

What is global trend in vertebrate species population numbers, both overall and how does it vary acrosss species and populations? 

## Step 2: Model building

Next we need to think about how we would build a model to address this question, with the goal to build the model and evaluate it using simulated data. There is a lot of demographic models in population ecology, so we might revisit those and consider a discrete time model based on population size and stepping through each year of data. We might also start with a simple linear model, where populations can go up, down or do nothing. That gets us started, but now we need to consider how we will model species and populations. Populations usually are nested in species in ecological models, so we might consider that to start. Our resulting model might then be:

y_i ~ normal(mu, sigma)

mu = alpha[sp[pop]] + beta[sp[pop]]*year 

*Need to finish the notation as I always have to look up the nesting notation.* 

## Step 3: Model evaluation 

Now we need to simulate data to test our model. As we start to think about how to do this, we may become overwhelmed with the scale of the question we started with. We likely would not feel immediately sure how to simulate for all different vertebrate species. 

### Stepping backward...

Here we would likely feedback one to two steps. We could step back to Step 2 and consider adding a phylogeny or other structure from which we could then simulate data from, or we could step back to Step 1 and narrow the question (before potentially building it back up.) We believe the latter approach is often better as working on a small scale first can point out more fundamental problems versus starting big and then spending much longer to identify fundamental problems. 

*Obviously we can charge forward with the full model if you want, I just thought this would be (a) easier for us, (b) way better to show as it's how you should do it and (c) related to a, I suspect JD can be more help, though any country with a good amount of data could work.* 
So here we refine our question to:

What is trend in terrestrial vertebrate species population numbers in South Africa, both overall and how does it vary acrosss species and populations? 

Now we start to simulate! 
*Sorry, I did not have time to do this, but I would simulate from the above model or some other simple one you come up with. I would simulate really NICE data, not realistic data.* 
```{r}

```
*Add some text here showing the model output returning paramaters.* 

## Step 4: Fit model to empirical data

Here we finally get to see how our model performs on the empirical data and are a step closer to answering our question, but we also start to notice some differences in our empirical data from our simulated data. In preparing our data for the model, we realize we have major gaps in sampling years and ... something else? 

Here, we might step back and adjust our model (re-doing Step 2-3 again), but in this case we go ahead.

*See starterLPI.R for what I have so far with the data...* 


## Step 5: Retrodictive check 

Now we check how well our model predicts our data ... 

## Feedbacks

At this point, we would have a lot of ideas of ways to improve this model that we would want to follow up on, including questioning our assumption of one sigma for all populations and potentially our linearity assumption. We also may want to add predictors for the slope such as  ... We would do this, returning to Steps 2-5 likely several times until we have a model that is good enough for our purposes here. 

And then we would likely add in more countries and species.... 

And then we would realize we really don't have great data for this question and we would ... 
